from open_ai.writer import writer_request
from open_ai.image_creator import image_prompt_request, image_request

def print_wait(content):
    print()
    print("### " + content + " ###")
    print()
    
def print_post(content):
    print()
    print('-' * 70)
    print(content)
    print('-' * 70)
    print()

def main():
    while True:
        # Ask for a prompt
        prompt = input("Please enter a prompt: ")
        if prompt.lower() in ['exit', 'quit']:
            print("Goodbye!")
            break

        # Request an instragram post based on the prompt
        print_wait("A post is being generated...")
        post = writer_request(prompt)
        print("The following post has been generated:")
        print_post(post["content"])
        
        answer = input("Do you want to create an image for your post? [YES/NO]\n")
        answer = answer.lower()
        print()
        
        while not answer in ['yes', 'no']:
            answer = input("Answer was not yes or no. Do you want to create an image prompt? [YES/NO]\n")
            answer = answer.lower()
        
        if answer == "yes":
            # Request a DALLE prompt based on the generated post
            print_wait("A prompt for DALLE is being generated...") 
            prompt = image_prompt_request(post["messages"])
            print("The following prompt has been generated for this post:")
            print_post(prompt["content"])
            
            img = input("Do you want to create an image for this prompt? [YES/NO]\n")
            
            if img.lower() == "yes":
                # Generate image with DALLE based on prompt
                print_wait("One or more images are being generated by DALLE...")
                image_request(prompt["content"])
        
# This ensures that the main function runs when the script is executed
if __name__ == "__main__":
    main()